export const DATA_ENTRY_CLEAR = 'dataEntry/CLEAR';
export const DATA_ENTRY_SET_SUBMISSION_IN_PROGRESS = 'dataEntry/SET_SUBMISSION_IN_PROGRESS';
export const DATA_ENTRY_SET_COMPLETED_CALCULATION = 'dataEntry/SET_COMPLETED_CALCULATION';
